### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by suculent** [insidegui/AssetCatalogTinkerer#13]
Hello, would it be feasible also to edit/import new image data into the CAR?

**Comment by insidegui** [comment]
I'm not sure. There are APIs for that, but I don't know if it would work well enough to be worth the effort.

**Comment by suculent** [comment]
Hello,

I’ll look into the sources and try it myself to see where it goes. Can you give some guidance as of to what APIs, where to start?

I would use it as it’s not possible to re-create the assets file without having source Xcode project, what typically does not happen when re-branding blackboxed apps with automation. We’re

Your tool just saved me lots of troubles today, because it showed there are un-overridden assets in the application.

Thanks,
Matej

**Comment by insidegui** [comment]
You'll need to `class-dump` `/System/Library/PrivateFrameworks/CoreUI`. You're probably looking for `CUIMutableCatalog` or `CUIMutableCommonAssetStorage`.

**Comment by insidegui** [comment]
**Important:** Be careful when using these mutable classes, make backups of the `car` files before loading them ;)

**Comment by suculent** [comment]
Thanks. It seems that `- (void)insertCGImage:(struct CGImage *)arg1 withName:(id)arg2 andDescription:(id)arg3;` should no it.

**Comment by suculent** [comment]
Well, it does "not respond" even though I’ve copied respective part of header. It seems I need to look into ThemeStore now.

self.catalog is initialized as CUIMutableCatalog now

```
- (void)insertImage:(NSImage *)image withName:(NSString *)arg2 andDescription:(NSString *)arg3 {
    NSRect imageRect = NSMakeRect(0, 0, image.size.width, image.size.height);
    CGImageRef cgImage = [image CGImageForProposedRect:&imageRect context:NULL hints:nil];
    [self.catalog insertCGImage:cgImage withName:arg2 andDescription:arg3];
    // TODO: add saving
}
```

	2017-01-09 23:00:45.788 Asset Catalog Tinkerer[29186:9492677] -[CUIMutableCatalog insertCGImage:withName:andDescription:] themeStore doesn't respond to insertCGImage:withName:andDescription: 

CoreUI.h additions:

```
@interface CUIMutableCatalog : CUICatalog
- (void)insertCGImage:(struct CGImage *)arg1 withName:(id)arg2 andDescription:(id)arg3;
- (void)insertCGImage:(struct CGImage *)arg1 name:(id)arg2 scale:(double)arg3 idiom:(long long)arg4 subtype:(long long)arg5;
- (id)initWithName:(id)arg1 fromBundle:(id)arg2 error:(id *)arg3;
- (id)init;
- (id)initWithName:(id)arg1;

@end

@interface CUIMutableStructuredThemeStore : CUIStructuredThemeStore
{
    NSString *_identifier;
    NSMutableDictionary *_memoryStore;
    NSMutableDictionary *_nameIdentifierStore;
    int _maxNameIdentifier;
}

- (void)clearRenditionCache;
- (void)removeImageNamed:(id)arg1 withDescription:(id)arg2;
- (void)insertCGImage:(struct CGImage *)arg1 withName:(id)arg2 andDescription:(id)arg3;
- (id)renditionWithKey:(const struct _renditionkeytoken *)arg1 usingKeySignature:(id)arg2;
- (id)renditionWithKey:(const struct _renditionkeytoken *)arg1;
- (BOOL)canGetRenditionWithKey:(const struct _renditionkeytoken *)arg1 isFPO:(char *)arg2;
- (BOOL)canGetRenditionWithKey:(const struct _renditionkeytoken *)arg1;
- (id)imagesWithName:(id)arg1;
- (const struct _renditionkeytoken *)renditionKeyForName:(id)arg1;
- (const struct _renditionkeytoken *)renditionKeyForName:(id)arg1 cursorHotSpot:(struct CGPoint *)arg2;
- (id)allImageNames;
- (const struct _renditionkeyfmt *)keyFormat;
- (BOOL)usesCUISystemThemeRenditionKey;
- (long long)maximumRenditionKeyTokenCount;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end


```

**Comment by suculent** [comment]
It was actually much safer and easier to use actool instead, and it works headless, no need to click.

/usr/bin/find -L $appDir -type d -name "*.xcassets" -print0 | \
xargs -0 $XCRUN -sdk iphoneos \
   actool --compile $appDir \
          --minimum-deployment-target ${minOSVersion} \
          --platform iphoneos --target-device ${targetDeviceParam} \
          --output-format human-readable-text \
          --compress-pngs \
          --notices \
          --warnings \
          --errors
