### ISSUE TITLE
Screenshots are outdated

### ISSUE THREAD

**Issue by saagarjha** [insidegui/AssetCatalogTinkerer#17]
I'm having an odd issue with Asset Catalog Tinkerer where it's using Helvetica Neue for its interface (but only in some places):

![screen shot 2017-03-13 at 22 26 28](https://cloud.githubusercontent.com/assets/13786931/23886983/2c85e220-083c-11e7-8353-1a20d3d8ca67.png)

Would you happen to know what's causing this? I'm using Asset Catalog Tinkerer Version 2.5 (250) on macOS Sierra 10.12.4 Beta (16E189a), FYI.

**Comment by insidegui** [comment]
This happens because the app is linked against ProKit to be able to read ProKit's asset catalogs.

**Comment by saagarjha** [comment]
So, is this the intended behavior? The screenshots you have in the README don't seem to have this issue.

**Comment by insidegui** [comment]
It's not necessarily intended, it's just a side effect from linking to ProKit. The screenshots don't show this because I took them before implementing ProKit support.

**Comment by saagarjha** [comment]
Ahh, got it. Quick question: how exactly does this occur? Does ProKit set Helvetica as the default font?

**Comment by saagarjha** [comment]
FYI: I managed to "fix" this by linking [Asset Catalog Tinkerer against ProKit.framework](https://github.com/saagarjha/AssetCatalogTinkerer/commit/8544421f2161608c6d9b180cf27c5225cf485e2b).

**Comment by insidegui** [comment]
> how exactly does this occur? Does ProKit set Helvetica as the default font?
Sort of. It does some method swizzling on `NSFont` so yeah, effectively that's what it does :)

I'll review your pull request later. Thanks!

**Comment by saagarjha** [comment]
Alright, I created #18.
