### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by nterbogt** [insidegui/AssetCatalogTinkerer#19]
The application isn't showing a bunch of Assets that I have in my catalog. Particularly the new types like Sprite Atlases and Apple TV image stacks, though some standard flat PNGs also aren't showing.

I know they are in the catalog because I can see them just viewing the binary in a text editor.

Is there a newer version of ACS that can be integrated?

**Comment by insidegui** [comment]
Not all rendition types are supported by ACT yet, I'm working on a new version that should be able to handle all of these other types of catalogs. If you can, please send me a sample file I can use to test this. Thanks

**Comment by nterbogt** [comment]
Thanks for getting back to me so quickly.

I won’t be able to provide you with the asset catalog until the product goes live on the aTV store. I’m happy to test development versions as you reach stable points, if you’d like.

Thanks for the application too, I think it’ll be really useful once I can view all the assets :)
