### ISSUE TITLE
Crash on macOS 10.13 beta

### ISSUE THREAD

**Issue by LeoNatan** [insidegui/AssetCatalogTinkerer#22]
> Dyld Error Message:
>   Library not loaded: /System/Library/PrivateFrameworks/ProKit.framework/Versions/A/ProKit
>   Referenced from: /Applications/Asset Catalog Tinkerer.app/Contents/Frameworks/ACS.framework/Versions/A/ACS
>   Reason: image not found

It seems like Apple has moved some frameworks around.

**Comment by insidegui** [comment]
I think ProKit is not used by any system app anymore, so they probably removed it for that reason. I'll have to change the link to an optional link so the app can work without it.

**Comment by LeoNatan** [comment]
Thanks for the amazing response time!

**Comment by wangjingjing115** [comment]
I met the same problem

**Comment by saagarjha** [comment]
@insidegui FYI #18 fixes this.

**Comment by insidegui** [comment]
@saagarjha Thanks for the PR

**Comment by canadaohcanada** [comment]
Could we get this updated version precompiled and placed into the 'Latest Release' link? The last link is from January 3rd and does not function on macOS High Sierra.

**Comment by canadaohcanada** [comment]
Thanks for the amazing turnaround. This newly-uploaded file works as expected on High Sierra.
