### ISSUE TITLE
Apple changed how Asset Catalogs are stored?

### ISSUE THREAD

**Issue by kylesethgray** [insidegui/AssetCatalogTinkerer#32]
On iOS 12, I can't seem to open any of the Asset catalogs on the seed - when opening directly from the dmg, I just get a locked error, and then when copying them to a read write volume, I just get this blank screen:
<img width="924" alt="screen shot 2018-06-10 at 8 00 08 am" src="https://user-images.githubusercontent.com/3441599/41202306-6707a1f6-6c84-11e8-9ce0-e402d8d75f14.png">

**Comment by insidegui** [comment]
Every new release tends to break things with asset catalogs. I’ll be working on fixing it when I have time. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by insidegui** [comment]
It looks like the title of your issue is 100% correct 😅 Apple introduced a new compression system in asset catalogs, so it's not possible to load iOS 12 / macOS Mojave catalogs while running High Sierra. So if you need to unpack iOS 12 content you'll need to be running Mojave.

**Comment by kylesethgray** [comment]
Ahaha amazing. Well I’ll be sure to upgrade to the public beta so I can continue poking around 👀
